### ISSUE TITLE
import collection with 2 modes once

### ISSUE THREAD

**Issue by eniris** [jake-figma/variables-import-export#4]
Hello, is it possible to import a variables collection with 2 modes once ?

**Comment by jake-figma** [comment]
it is definitely possible with the plugin api, but not with this plugin. this plugin is structured around importing the current w3c spec for tokens, which doesnt really have a native way to model multiple modes yet. the easiest way to do this with this plugin would be to import two separate json objects, one for each mode.

if you were interested in building your own plugin to do this, you can find more info on multiple modes [in the docs](https://www.figma.com/plugin-docs/working-with-variables/#example-authoring-a-new-variable-collection), but it would be something like this:

```js
const collection = figma.variables.createVariableCollection("new-collection")
collection.renameMode(collection.modes[0].modeId, "light")
const colorVariable = figma.variables.createVariable("color-variable", collection.id, "COLOR")

// rename our new variable and collection because naming is hard!
colorVariable.name = "text-primary"
collection.name = "semantic colors"

const lightModeId = collection.modes[0].modeId
const darkModeId = collection.addMode("dark")

// Sets the color to #000 in light mode and #fff in dark mode
colorVariable.setValueForMode(lightModeId, {r: 0, g: 0, b: 0})
colorVariable.setValueForMode(darkModeId, {r: 1, g: 1, b: 1})
```
